import type { DeployOption } from "@app-types";

export const deployOptions: DeployOption[] = [
  { chain: "Base", chainId: 8453, type: "mainnet", icon: "base.jpg", fee: 0.000045, color: "#0000FF" },
  { chain: "Optimism", chainId: 10, type: "mainnet", icon: "optimism.png", fee: 0.000045, color: "#FF0420" },
  { chain: "Unichain", chainId: 130, type: "mainnet", icon: "unichain.png", fee: 0.000045, color: "#F51BBD" },
  { chain: "Soneium", chainId: 1868, type: "mainnet", icon: "soneium.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Sonic", chainId: 146, type: "mainnet", icon: "sonic.svg", fee: 0.2, color: "#FFF" },
  { chain: "Polygon", chainId: 137, type: "mainnet", icon: "polygon.svg", fee: 0.4, color: "#FFF" },
  { chain: "HyperEVM", chainId: 999, type: "mainnet", icon: "hyperevm.svg", fee: 0.002, color: "#FFF" },
  { chain: "Sei", chainId: 1329, type: "mainnet", icon: "sei.svg", fee: 0.4, color: "#FFF" },
  { chain: "Scroll", chainId: 534352, type: "mainnet", icon: "scroll.png", fee: 0.000015, color: "#FFF" },
  { chain: "Lens", chainId: 232, type: "mainnet", icon: "lens.svg", fee: 0.1, color: "#FFF" },
  { chain: "Linea", chainId: 59144, type: "mainnet", icon: "linea.png", fee: 0.000045, color: "#FFF" },
  { chain: "Morph", chainId: 2818, type: "mainnet", icon: "morph.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Berachain", chainId: 80094, type: "mainnet", icon: "berachain.svg", fee: 0.06, color: "#FFF" },
  { chain: "Abstract", chainId: 2741, type: "mainnet", icon: "abstract.png", fee: 0.000045, color: "#FFF" },
  { chain: "Mantle", chainId: 5000, type: "mainnet", icon: "mantle.svg", fee: 0.2, color: "#FFF" },
  { chain: "Ink", chainId: 57073, type: "mainnet", icon: "ink.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Mode", chainId: 34443, type: "mainnet", icon: "mode.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Orderly", chainId: 291, type: "mainnet", icon: "orderly.svg", fee: 0.000045, color: "#FFF" },
  { chain: "ApeChain", chainId: 33139, type: "mainnet", icon: "apechain.svg", fee: 0.2, color: "#FFF" },
  { chain: "zkSync Era", chainId: 324, type: "mainnet", icon: "zksync.png", fee: 0.000045, color: "#FFF" },
  { chain: "Hemi", chainId: 43111, type: "mainnet", icon: "hemi.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Lisk", chainId: 1135, type: "mainnet", icon: "lisk.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Taiko", chainId: 167000, type: "mainnet", icon: "taiko.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Mint", chainId: 185, type: "mainnet", icon: "mint.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Blast", chainId: 81457, type: "mainnet", icon: "blast.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Polygon zkEVM", chainId: 1101, type: "mainnet", icon: "polygonzkevm.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Manta Pacific", chainId: 169, type: "mainnet", icon: "mantapacific.svg", fee: 0.000045, color: "#FFF" },
  { chain: "BOB", chainId: 60808, type: "mainnet", icon: "bob.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Fraxtal", chainId: 252, type: "mainnet", icon: "fraxtal.svg", fee: 0.05, color: "#FFF" },
  { chain: "Story", chainId: 1514, type: "mainnet", icon: "story.svg", fee: 0.03, color: "#FFF" },
  { chain: "Avalanche", chainId: 43114, type: "mainnet", icon: "avalanche.svg", fee: 0.0065, color: "#FFF" },
  { chain: "Canto", chainId: 7700, type: "mainnet", icon: "canto.svg", fee: 2, color: "#FFF" },
  { chain: "BSC", chainId: 56, type: "mainnet", icon: "bsc.svg", fee: 0.0002, color: "#FFF" },
  { chain: "Moonbeam", chainId: 1284, type: "mainnet", icon: "moonbeam.svg", fee: 1, color: "#FFF" },
  { chain: "Moonriver", chainId: 1285, type: "mainnet", icon: "moonriver.svg", fee: 0.01, color: "#FFF" },
  { chain: "Astar", chainId: 592, type: "mainnet", icon: "astar.svg", fee: 5, color: "#FFF" },
  { chain: "Conflux eSpace", chainId: 1030, type: "mainnet", icon: "conflux.svg", fee: 1, color: "#FFF" },
  { chain: "Beam", chainId: 4337, type: "mainnet", icon: "beam.svg", fee: 15, color: "#FFF" },
  { chain: "Chiliz", chainId: 88888, type: "mainnet", icon: "chiliz.svg", fee: 2.5, color: "#FFF" },
  { chain: "World Chain", chainId: 480, type: "mainnet", icon: "worldchain.svg", fee: 0.000045, color: "#FFF" },
  { chain: "Shibarium", chainId: 109, type: "mainnet", icon: "shibarium.svg", fee: 1, color: "#FFF" },
  { chain: "Flare", chainId: 14, type: "mainnet", icon: "flare.svg", fee: 5, color: "#FFF" },
  { chain: "Degen", chainId: 666666666, type: "mainnet", icon: "degen.png", fee: 20, color: "#FFF" },
  { chain: "Xai", chainId: 660279, type: "mainnet", icon: "xai.svg", fee: 1, color: "#FFF" },
  { chain: "Kava", chainId: 2222, type: "mainnet", icon: "kava.svg", fee: 0.02, color: "#FFF" },
  { chain: "Aurora", chainId: 1313161554, type: "mainnet", icon: "aurora.svg", fee: 0.000045, color: "#FFF" },
  { chain: "ZetaChain", chainId: 7000, type: "mainnet", icon: "zetachain.svg", fee: 0.5, color: "#FFF" },
  { chain: "Cronos", chainId: 25, type: "mainnet", icon: "cronos.png", fee: 1, color: "#FFF" },
  { chain: "Botanix", chainId: 3637, type: "mainnet", icon: "botanix.png", fee: 0.000005, color: "#FFF" },
  { chain: "Katana", chainId: 747474, type: "mainnet", icon: "katana.svg", fee: 0.000005, color: "#FFF" },
  { chain: "Sepolia Testnet", chainId: 11155111, type: "testnet", icon: "sepolia.png", fee: 0.00005, color: "#FFF" },
  { chain: "Monad Testnet", chainId: 10143, type: "testnet", icon: "monad.png", fee: 0.01, color: "#FFF" },
  { chain: "Rise Testnet", chainId: 11155931, type: "testnet", icon: "rise.svg", fee: 0.0001, color: "#FFF" },
  { chain: "Somnia Testnet", chainId: 50312, type: "testnet", icon: "somnia.svg", fee: 0.1, color: "#FFF" },
  { chain: "Pharos Testnet", chainId: 688688, type: "testnet", icon: "pharos.png", fee: 0.005, color: "#FFF" },
  { chain: "Citrea Testnet", chainId: 5115, type: "testnet", icon: "citrea.png", fee: 0.000005, color: "#FFF" },
  { chain: "Moca Chain Testnet", chainId: 5151, type: "testnet", icon: "moca.png", fee: 0.00002, color: "#FFF" },
  { chain: "0G Galileo Testnet", chainId: 16601, type: "testnet", icon: "0glabs.png", fee: 0.00001, color: "#FFF" },
  { chain: "MegaETH Testnet", chainId: 6342, type: "testnet", icon: "megaeth.png", fee: 0.00001, color: "#FFF" },
  { chain: "XOS Testnet", chainId: 1267, type: "testnet", icon: "xos.png", fee: 0.00005, color: "#FFF" },
  { chain: "Bloch Chain Testkek", chainId: 6231991, type: "testnet", icon: "blockchain.jpg", fee: 0.00002, color: "#FFF" },
  { chain: "Fluent Testnet", chainId: 20994, type: "testnet", icon: "fluent.jpg", fee: 0.000033, color: "#FFF" },
  { chain: "Giwa Testnet", chainId: 91342, type: "testnet", icon: "giwa.jpg", fee: 0.000015, color: "#FFF" },
  { chain: "Neura Testnet", chainId: 267, type: "testnet", icon: "neura.jpg", fee: 0.000004, color: "#FFF" }
];
