import type { DeployOption } from "@app-types";

export const deployOptions: DeployOption[] = [
  { chain: "Base", chainId: 8453, type: "mainnet", icon: "base.png", fee: 0.000045 },
  { chain: "Optimism", chainId: 10, type: "mainnet", icon: "optimism.png", fee: 0.000045 },
  { chain: "Unichain", chainId: 130, type: "mainnet", icon: "unichain.png", fee: 0.000045 },
  { chain: "Soneium", chainId: 1868, type: "mainnet", icon: "soneium.svg", fee: 0.000045 },
  { chain: "Sonic", chainId: 146, type: "mainnet", icon: "sonic.svg", fee: 0.2 },
  { chain: "Polygon", chainId: 137, type: "mainnet", icon: "polygon.svg", fee: 0.4 },
  { chain: "Sei", chainId: 1329, type: "mainnet", icon: "sei.svg", fee: 0.4 },
  { chain: "Scroll", chainId: 534352, type: "mainnet", icon: "scroll.png", fee: 0.000015 },
  { chain: "Lens", chainId: 232, type: "mainnet", icon: "lens.svg", fee: 0.1 },
  { chain: "Linea", chainId: 59144, type: "mainnet", icon: "linea.png", fee: 0.000045 },
  { chain: "Morph", chainId: 2818, type: "mainnet", icon: "morph.svg", fee: 0.000045 },
  { chain: "Berachain", chainId: 80085, type: "mainnet", icon: "berachain.svg", fee: 0.06 },
  { chain: "Abstract", chainId: 2741, type: "mainnet", icon: "abstract.png", fee: 0.000045 },
  { chain: "Mantle", chainId: 5000, type: "mainnet", icon: "mantle.svg", fee: 0.2 },
  { chain: "Ink", chainId: 57073, type: "mainnet", icon: "ink.svg", fee: 0.000045 },
  { chain: "Mode", chainId: 34443, type: "mainnet", icon: "mode.svg", fee: 0.000045 },
  { chain: "Orderly", chainId: 291, type: "mainnet", icon: "orderly.svg", fee: 0.000045 },
  { chain: "ApeChain", chainId: 33139, type: "mainnet", icon: "apechain.svg", fee: 0.2 },
  { chain: "zkSync Era", chainId: 324, type: "mainnet", icon: "zksync.png", fee: 0.000045 },
  { chain: "Hemi", chainId: 43111, type: "mainnet", icon: "hemi.svg", fee: 0.000045 },
  { chain: "Lisk", chainId: 1135, type: "mainnet", icon: "lisk.svg", fee: 0.000045 },
  { chain: "Taiko", chainId: 167000, type: "mainnet", icon: "taiko.svg", fee: 0.000045 },
  { chain: "Mint", chainId: 185, type: "mainnet", icon: "mint.svg", fee: 0.000045 },
  { chain: "Blast", chainId: 81457, type: "mainnet", icon: "blast.svg", fee: 0.000045 },
  { chain: "Plume", chainId: 98866, type: "mainnet", icon: "plume.svg", fee: 2 },
  { chain: "Polygon zkEVM", chainId: 1101, type: "mainnet", icon: "polygonzkevm.svg", fee: 0.000045 },
  { chain: "Manta Pacific", chainId: 169, type: "mainnet", icon: "mantapacific.svg", fee: 0.000045 },
  { chain: "BOB", chainId: 60808, type: "mainnet", icon: "bob.svg", fee: 0.000045 },
  { chain: "Fraxtal", chainId: 252, type: "mainnet", icon: "fraxtal.svg", fee: 0.05 },
  { chain: "Story", chainId: 1514, type: "mainnet", icon: "story.svg", fee: 0.03 },
  { chain: "Avalanche", chainId: 43114, type: "mainnet", icon: "avalanche.svg", fee: 0.0065 },
  { chain: "Canto", chainId: 7700, type: "mainnet", icon: "canto.svg", fee: 2 },
  { chain: "BSC", chainId: 56, type: "mainnet", icon: "bsc.svg", fee: 0.0002 },
  { chain: "Moonbeam", chainId: 1284, type: "mainnet", icon: "moonbeam.svg", fee: 1 },
  { chain: "Moonriver", chainId: 1285, type: "mainnet", icon: "moonriver.svg", fee: 0.01 },
  { chain: "Astar", chainId: 592, type: "mainnet", icon: "astar.svg", fee: 5 },
  { chain: "Conflux eSpace", chainId: 1030, type: "mainnet", icon: "conflux.svg", fee: 1 },
  { chain: "Beam", chainId: 4337, type: "mainnet", icon: "beam.svg", fee: 15 },
  { chain: "Chiliz", chainId: 88888, type: "mainnet", icon: "chiliz.svg", fee: 2.5 },
  { chain: "World Chain", chainId: 480, type: "mainnet", icon: "worldchain.svg", fee: 0.000045 },
  { chain: "Shibarium", chainId: 109, type: "mainnet", icon: "shibarium.svg", fee: 1 },
  { chain: "Flare", chainId: 14, type: "mainnet", icon: "flare.svg", fee: 5 },
  { chain: "Degen", chainId: 666666666, type: "mainnet", icon: "degen.png", fee: 20 },
  { chain: "Xai", chainId: 660279, type: "mainnet", icon: "xai.svg", fee: 1 },
  { chain: "Kava", chainId: 2222, type: "mainnet", icon: "kava.svg", fee: 0.02 },
  { chain: "Sepolia Testnet", chainId: 11155111, type: "testnet", icon: "sepolia.png", fee: 0.0005 },
  { chain: "Monad Testnet", chainId: 10143, type: "testnet", icon: "monad.png", fee: 0.01 },
  { chain: "Rise Testnet", chainId: 11155931, type: "testnet", icon: "rise.svg", fee: 0.0001 },
  { chain: "Somnia Testnet", chainId: 50312, type: "testnet", icon: "somnia.svg", fee: 0.1 }
];
