import type { DeployOption } from "@app-types";

const mainnetOptions: DeployOption[] = [
  { chain: "Base", chainId: 8453, type: "mainnet", icon: "base.jpg", fee: 0.000045, color: "#0000FF", textColor: "#FFF", tags: ["hot"] },
  { chain: "Optimism", chainId: 10, type: "mainnet", icon: "optimism.png", fee: 0.000045, color: "#FF0420", textColor: "#FFF", tags: [] },
  { chain: "Unichain", chainId: 130, type: "mainnet", icon: "unichain.png", fee: 0.000045, color: "#F51BBD", textColor: "#FFF", tags: ["hot"] },
  { chain: "Soneium", chainId: 1868, type: "mainnet", icon: "soneium.svg", fee: 0.000045, color: "#6398C7", textColor: "#FFF", tags: ["hot"] },
  { chain: "Sonic", chainId: 146, type: "mainnet", icon: "sonic.svg", fee: 0.2, color: "#FFF", textColor: "#000", tags: ["hot"] },
  { chain: "Polygon", chainId: 137, type: "mainnet", icon: "polygon.svg", fee: 0.4, color: "#6600FF", textColor: "#FFF", tags: [] },
  { chain: "HyperEVM", chainId: 999, type: "mainnet", icon: "hyperevm.svg", fee: 0.002, color: "#97FCE4", textColor: "#000", tags: ["hot"] },
  { chain: "Sei", chainId: 1329, type: "mainnet", icon: "sei.svg", fee: 0.4, color: "#901111", textColor: "#FFF", tags: [] },
  { chain: "Scroll", chainId: 534352, type: "mainnet", icon: "scroll.png", fee: 0.000015, color: "#FFEEDA", textColor: "#000", tags: [] },
  { chain: "Arbitrum", chainId: 42161, type: "mainnet", icon: "arbitrum.jpg", fee: 0.000015, color: "#FFF", textColor: "#000", tags: [] },
  { chain: "Lens", chainId: 232, type: "mainnet", icon: "lens.svg", fee: 0.1, color: "#FFF", textColor: "#000", tags: [] },
  { chain: "Linea", chainId: 59144, type: "mainnet", icon: "linea.png", fee: 0.000045, color: "#61DFFF", textColor: "#FFF", tags: ["hot"] },
  { chain: "Morph", chainId: 2818, type: "mainnet", icon: "morph.svg", fee: 0.000045, color: "#14A800", textColor: "#FFF", tags: [] },
  { chain: "Berachain", chainId: 80094, type: "mainnet", icon: "berachain.svg", fee: 0.06, color: "#451D07", textColor: "#FFF", tags: [] },
  { chain: "Abstract", chainId: 2741, type: "mainnet", icon: "abstract.png", fee: 0.000045, color: "#01CA6A", textColor: "#FFF", tags: ["hot"] },
  { chain: "Mantle", chainId: 5000, type: "mainnet", icon: "mantle.svg", fee: 0.2, color: "#000", textColor: "#FFF", tags: [] },
  { chain: "Ink", chainId: 57073, type: "mainnet", icon: "ink.svg", fee: 0.000045, color: "#9E7CEB", textColor: "#FFF", tags: ["hot"] },
  { chain: "Mode", chainId: 34443, type: "mainnet", icon: "mode.svg", fee: 0.000045, color: "#DFFE00", textColor: "#000", tags: [] },
  { chain: "Orderly", chainId: 291, type: "mainnet", icon: "orderly.svg", fee: 0.000045, color: "#6D33B0", textColor: "#FFF", tags: [] },
  { chain: "ApeChain", chainId: 33139, type: "mainnet", icon: "apechain.svg", fee: 0.2, color: "#4B35FA", textColor: "#FFF", tags: [] },
  { chain: "zkSync Era", chainId: 324, type: "mainnet", icon: "zksync.png", fee: 0.000045, color: "#FFF", textColor: "#000", tags: [] },
  { chain: "Hemi", chainId: 43111, type: "mainnet", icon: "hemi.svg", fee: 0.000045, color: "#FF6C15", textColor: "#FFF", tags: ["hot"] },
  { chain: "Lisk", chainId: 1135, type: "mainnet", icon: "lisk.svg", fee: 0.000045, color: "#FFF", textColor: "#000", tags: [] },
  { chain: "Taiko", chainId: 167000, type: "mainnet", icon: "taiko.svg", fee: 0.000045, color: "#E81899", textColor: "#FFF", tags: [] },
  { chain: "Mint", chainId: 185, type: "mainnet", icon: "mint.svg", fee: 0.000045, color: "#30BF54", textColor: "#FFF", tags: [] },
  { chain: "Blast", chainId: 81457, type: "mainnet", icon: "blast.svg", fee: 0.000045, color: "#000", textColor: "#FFF", tags: [] },
  { chain: "Polygon zkEVM", chainId: 1101, type: "mainnet", icon: "polygonzkevm.svg", fee: 0.000045, color: "#935AE4", textColor: "#FFF", tags: [] },
  { chain: "Manta Pacific", chainId: 169, type: "mainnet", icon: "mantapacific.svg", fee: 0.000045, color: "#23C3C4", textColor: "#FFF", tags: [] },
  { chain: "BOB", chainId: 60808, type: "mainnet", icon: "bob.svg", fee: 0.000045, color: "#F25D00", textColor: "#FFF", tags: [] },
  { chain: "Fraxtal", chainId: 252, type: "mainnet", icon: "fraxtal.svg", fee: 0.05, color: "#000", textColor: "#FFF", tags: [] },
  { chain: "Story", chainId: 1514, type: "mainnet", icon: "story.svg", fee: 0.03, color: "#FFF", textColor: "#000", tags: [] },
  { chain: "Avalanche", chainId: 43114, type: "mainnet", icon: "avalanche.svg", fee: 0.0065, color: "#E84142", textColor: "#FFF", tags: ["hot"] },
  { chain: "Canto", chainId: 7700, type: "mainnet", icon: "canto.svg", fee: 2, color: "#06FC99", textColor: "#000", tags: [] },
  { chain: "BSC", chainId: 56, type: "mainnet", icon: "bsc.svg", fee: 0.0002, color: "#D6A50E", textColor: "#FFF", tags: [] },
  { chain: "Moonbeam", chainId: 1284, type: "mainnet", icon: "moonbeam.svg", fee: 1, color: "#AD166A", textColor: "#FFF", tags: [] },
  { chain: "Moonriver", chainId: 1285, type: "mainnet", icon: "moonriver.svg", fee: 0.01, color: "#326D7A", textColor: "#FFF", tags: [] },
  { chain: "Astar", chainId: 592, type: "mainnet", icon: "astar.svg", fee: 5, color: "#1F8DEE", textColor: "#FFF", tags: [] },
  { chain: "Conflux", chainId: 1030, type: "mainnet", icon: "conflux.svg", fee: 1, color: "#1BAD8D", textColor: "#FFF", tags: [] },
  { chain: "Beam", chainId: 4337, type: "mainnet", icon: "beam.svg", fee: 15, color: "#BBDBFF", textColor: "#000", tags: [] },
  { chain: "Chiliz", chainId: 88888, type: "mainnet", icon: "chiliz.svg", fee: 2.5, color: "#FF004B", textColor: "#FFF", tags: [] },
  { chain: "World Chain", chainId: 480, type: "mainnet", icon: "worldchain.svg", fee: 0.000045, color: "#FFF", textColor: "#000", tags: ["hot"] },
  { chain: "Shibarium", chainId: 109, type: "mainnet", icon: "shibarium.svg", fee: 1, color: "#FFAF28", textColor: "#FFF", tags: [] },
  { chain: "Flare", chainId: 14, type: "mainnet", icon: "flare.svg", fee: 5, color: "#E62359", textColor: "#FFF", tags: [] },
  { chain: "Degen", chainId: 666666666, type: "mainnet", icon: "degen.png", fee: 20, color: "#A36EFE", textColor: "#FFF", tags: [] },
  { chain: "Xai", chainId: 660279, type: "mainnet", icon: "xai.svg", fee: 1, color: "#F30019", textColor: "#FFF", tags: [] },
  { chain: "Kava", chainId: 2222, type: "mainnet", icon: "kava.svg", fee: 0.02, color: "#FF443F", textColor: "#FFF", tags: [] },
  { chain: "Aurora", chainId: 1313161554, type: "mainnet", icon: "aurora.svg", fee: 0.000045, color: "#59A540", textColor: "#FFF", tags: [] },
  { chain: "ZetaChain", chainId: 7000, type: "mainnet", icon: "zetachain.svg", fee: 0.5, color: "#005741", textColor: "#FFF", tags: [] },
  { chain: "Cronos", chainId: 25, type: "mainnet", icon: "cronos.png", fee: 1, color: "#000", textColor: "#FFF", tags: ["hot"] },
  { chain: "Botanix", chainId: 3637, type: "mainnet", icon: "botanix.png", fee: 0.000005, color: "#FACD02", textColor: "#000", tags: [] },
  { chain: "Katana", chainId: 747474, type: "mainnet", icon: "katana.svg", fee: 0.000005, color: "#F4FF00", textColor: "#000", tags: ["hot"] },
  { chain: "Plume", chainId: 98866, type: "mainnet", icon: "plume.jpg", fee: 0.03, color: "#FF3C00", textColor: "#FFF", tags: ["hot"] },
  { chain: "XDC", chainId: 50, type: "mainnet", icon: "xdc.jpg", fee: 0.03, color: "#244C80", textColor: "#FFF", tags: [] },
  { chain: "Mezo", chainId: 31612, type: "mainnet", icon: "mezo.jpg", fee: 0.03, color: "#FF004C", textColor: "#FFF", tags: [] },
  { chain: "Kaia", chainId: 8217, type: "mainnet", icon: "kaia.jpg", fee: 0.025, color: "#BFF009", textColor: "#000", tags: [] },
  { chain: "JuChain", chainId: 210000, type: "mainnet", icon: "juchain.jpg", fee: 0.01, color: "#153BFE", textColor: "#FFF", tags: ["hot"] },
  { chain: "Mitosis", chainId: 124816, type: "mainnet", icon: "mitosis.jpg", fee: 0.2, color: "#5E5DF7", textColor: "#FFF", tags: ["hot"] }
];

const testnetOptions: DeployOption[] = [
  { chain: "Sepolia Testnet", chainId: 11155111, type: "testnet", icon: "sepolia.png", fee: 0.00005, color: "#627EEA", textColor: "#FFF", tags: [] },
  { chain: "Monad Testnet", chainId: 10143, type: "testnet", icon: "monad.png", fee: 0.01, color: "#8070F2", textColor: "#FFF", tags: [] },
  { chain: "Rise Testnet", chainId: 11155931, type: "testnet", icon: "rise.svg", fee: 0.0001, color: "#7A67E5", textColor: "#FFF", tags: [] },
  { chain: "Somnia Testnet", chainId: 50312, type: "testnet", icon: "somnia.svg", fee: 0.1, color: "#483BF6", textColor: "#FFF", tags: [] },
  { chain: "Pharos Testnet", chainId: 688688, type: "testnet", icon: "pharos.png", fee: 0.005, color: "#0007B8", textColor: "#FFF", tags: ["hot"] },
  { chain: "Citrea Testnet", chainId: 5115, type: "testnet", icon: "citrea.png", fee: 0.000005, color: "#E47530", textColor: "#FFF", tags: [] },
  { chain: "Moca Testnet", chainId: 5151, type: "testnet", icon: "moca.png", fee: 0.00002, color: "#C15F97", textColor: "#FFF", tags: [] },
  { chain: "0G Testnet", chainId: 16601, type: "testnet", icon: "0glabs.png", fee: 0.00001, color: "#BA51FA", textColor: "#FFF", tags: [] },
  { chain: "MegaETH Testnet", chainId: 6342, type: "testnet", icon: "megaeth.png", fee: 0.00001, color: "#DFD9D9", textColor: "#000", tags: [] },
  { chain: "XOS Testnet", chainId: 1267, type: "testnet", icon: "xos.png", fee: 0.00005, color: "#000", textColor: "#FFF", tags: ["hot"] },
  { chain: "Block Chain Testkek", chainId: 6231991, type: "testnet", icon: "blockchain.jpg", fee: 0.00002, color: "#0000FF", textColor: "#FFF", tags: ["hot"] },
  { chain: "Fluent Testnet", chainId: 20994, type: "testnet", icon: "fluent.jpg", fee: 0.000033, color: "#000", textColor: "#FFF", tags: [] },
  { chain: "Giwa Testnet", chainId: 91342, type: "testnet", icon: "giwa.jpg", fee: 0.000015, color: "#FFF", textColor: "#000", tags: ["hot"] },
  { chain: "Neura Testnet", chainId: 267, type: "testnet", icon: "neura.jpg", fee: 0.000004, color: "#7FFF76", textColor: "#000", tags: ["hot", "new"] },
  { chain: "KiteAI Testnet", chainId: 2368, type: "testnet", icon: "kiteai.jpg", fee: 0.0001, color: "#000", textColor: "#FFF", tags: ["hot", "new"] },
  { chain: "Kii Testnet", chainId: 1336, type: "testnet", icon: "kii.jpg", fee: 0.000025, color: "#332976", textColor: "#FFF", tags: [] }
];

export const deployOptions: DeployOption[] = [...mainnetOptions, ...testnetOptions];
