import { DeployTypes } from "@app-enums";
import type { DeployOption } from "@app-types";

const approvedRecords = [
  "Thriller",
  "Back in Black",
  "The Bodyguard",
  "The Dark Side of the Moon",
  "Their Greatest Hits (1971-1975)",
  "Hotel California",
  "Come On Over",
  "Rumours",
  "Saturday Night Fever",
];

const mainnetOptions: DeployOption[] = [
  { chain: "Base", chainId: 8453, type: "mainnet", icon: "base.jpg", fee: 0.000025, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Optimism", chainId: 10, type: "mainnet", icon: "optimism.png", fee: 0.000025, backgroundColor: "#FF0420", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Unichain", chainId: 130, type: "mainnet", icon: "unichain.png", fee: 0.000025, backgroundColor: "#F51BBD", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Soneium", chainId: 1868, type: "mainnet", icon: "soneium.svg", fee: 0.000025, backgroundColor: "#6398C7", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Sonic", chainId: 146, type: "mainnet", icon: "sonic.svg", fee: 0.2, backgroundColor: "#FFFFFF", color: "#000000", tags: ["hot"] },
  { chain: "Polygon", chainId: 137, type: "mainnet", icon: "polygon.svg", fee: 0.4, backgroundColor: "#6600FF", color: "#FFFFFF", tags: [] },
  { chain: "HyperEVM", chainId: 999, type: "mainnet", icon: "hyperevm.svg", fee: 0.002, backgroundColor: "#97FCE4", color: "#000000", tags: ["hot"] },
  { chain: "Sei", chainId: 1329, type: "mainnet", icon: "sei.svg", fee: 0.4, backgroundColor: "#901111", color: "#FFFFFF", tags: [] },
  { chain: "Scroll", chainId: 534352, type: "mainnet", icon: "scroll.png", fee: 0.000015, backgroundColor: "#FFEEDA", color: "#000000", tags: [] },
  { chain: "Arbitrum", chainId: 42161, type: "mainnet", icon: "arbitrum.jpg", fee: 0.000015, backgroundColor: "#FFFFFF", color: "#000000", tags: [] },
  { chain: "Lens", chainId: 232, type: "mainnet", icon: "lens.svg", fee: 0.1, backgroundColor: "#FFFFFF", color: "#000000", tags: ["hot"] },
  { chain: "Linea", chainId: 59144, type: "mainnet", icon: "linea.png", fee: 0.000025, backgroundColor: "#61DFFF", color: "#000000", tags: ["hot"] },
  { chain: "Morph", chainId: 2818, type: "mainnet", icon: "morph.svg", fee: 0.000025, backgroundColor: "#14A800", color: "#FFFFFF", tags: [] },
  { chain: "Berachain", chainId: 80094, type: "mainnet", icon: "berachain.svg", fee: 0.06, backgroundColor: "#451D07", color: "#FFFFFF", tags: [] },
  { chain: "Abstract", chainId: 2741, type: "mainnet", icon: "abstract.png", fee: 0.000025, backgroundColor: "#01CA6A", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Mantle", chainId: 5000, type: "mainnet", icon: "mantle.svg", fee: 0.2, backgroundColor: "#000000", color: "#FFFFFF", tags: [] },
  { chain: "Ink", chainId: 57073, type: "mainnet", icon: "ink.svg", fee: 0.000025, backgroundColor: "#9E7CEB", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Mode", chainId: 34443, type: "mainnet", icon: "mode.svg", fee: 0.000025, backgroundColor: "#DFFE00", color: "#000000", tags: [] },
  { chain: "Orderly", chainId: 291, type: "mainnet", icon: "orderly.svg", fee: 0.000025, backgroundColor: "#6D33B0", color: "#FFFFFF", tags: [] },
  { chain: "ApeChain", chainId: 33139, type: "mainnet", icon: "apechain.svg", fee: 0.2, backgroundColor: "#4B35FA", color: "#FFFFFF", tags: [] },
  { chain: "zkSync Era", chainId: 324, type: "mainnet", icon: "zksync.png", fee: 0.000025, backgroundColor: "#FFFFFF", color: "#000000", tags: [] },
  { chain: "Hemi", chainId: 43111, type: "mainnet", icon: "hemi.svg", fee: 0.000025, backgroundColor: "#FF6C15", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Lisk", chainId: 1135, type: "mainnet", icon: "lisk.svg", fee: 0.000025, backgroundColor: "#FFFFFF", color: "#000000", tags: ["hot"] },
  { chain: "Taiko", chainId: 167000, type: "mainnet", icon: "taiko.svg", fee: 0.000025, backgroundColor: "#E81899", color: "#FFFFFF", tags: [] },
  { chain: "Mint", chainId: 185, type: "mainnet", icon: "mint.svg", fee: 0.000025, backgroundColor: "#30BF54", color: "#FFFFFF", tags: [] },
  { chain: "Blast", chainId: 81457, type: "mainnet", icon: "blast.svg", fee: 0.000025, backgroundColor: "#000000", color: "#FFFFFF", tags: [] },
  { chain: "Polygon zkEVM", chainId: 1101, type: "mainnet", icon: "polygonzkevm.svg", fee: 0.000025, backgroundColor: "#935AE4", color: "#FFFFFF", tags: [] },
  { chain: "Manta Pacific", chainId: 169, type: "mainnet", icon: "mantapacific.svg", fee: 0.000025, backgroundColor: "#23C3C4", color: "#FFFFFF", tags: [] },
  { chain: "BOB", chainId: 60808, type: "mainnet", icon: "bob.svg", fee: 0.000025, backgroundColor: "#F25D00", color: "#FFFFFF", tags: [] },
  { chain: "Fraxtal", chainId: 252, type: "mainnet", icon: "fraxtal.svg", fee: 0.05, backgroundColor: "#000000", color: "#FFFFFF", tags: [] },
  { chain: "Story", chainId: 1514, type: "mainnet", icon: "story.svg", fee: 0.03, backgroundColor: "#FFFFFF", color: "#000000", tags: [] },
  { chain: "Avalanche", chainId: 43114, type: "mainnet", icon: "avalanche.svg", fee: 0.0065, backgroundColor: "#E84142", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Canto", chainId: 7700, type: "mainnet", icon: "canto.svg", fee: 2, backgroundColor: "#06FC99", color: "#000000", tags: [] },
  { chain: "BSC", chainId: 56, type: "mainnet", icon: "bsc.svg", fee: 0.0002, backgroundColor: "#D6A50E", color: "#FFFFFF", tags: [] },
  { chain: "Moonbeam", chainId: 1284, type: "mainnet", icon: "moonbeam.svg", fee: 1, backgroundColor: "#AD166A", color: "#FFFFFF", tags: [] },
  { chain: "Moonriver", chainId: 1285, type: "mainnet", icon: "moonriver.svg", fee: 0.01, backgroundColor: "#326D7A", color: "#FFFFFF", tags: [] },
  { chain: "Astar", chainId: 592, type: "mainnet", icon: "astar.svg", fee: 5, backgroundColor: "#1F8DEE", color: "#FFFFFF", tags: [] },
  { chain: "Conflux", chainId: 1030, type: "mainnet", icon: "conflux.svg", fee: 1, backgroundColor: "#1BAD8D", color: "#FFFFFF", tags: [] },
  { chain: "Beam", chainId: 4337, type: "mainnet", icon: "beam.svg", fee: 15, backgroundColor: "#BBDBFF", color: "#000000", tags: [] },
  { chain: "Chiliz", chainId: 88888, type: "mainnet", icon: "chiliz.svg", fee: 2.5, backgroundColor: "#FF004B", color: "#FFFFFF", tags: [] },
  { chain: "World Chain", chainId: 480, type: "mainnet", icon: "worldchain.svg", fee: 0.000025, backgroundColor: "#FFFFFF", color: "#000000", tags: [] },
  { chain: "Shibarium", chainId: 109, type: "mainnet", icon: "shibarium.svg", fee: 1, backgroundColor: "#FFAF28", color: "#FFFFFF", tags: [] },
  { chain: "Flare", chainId: 14, type: "mainnet", icon: "flare.svg", fee: 5, backgroundColor: "#E62359", color: "#FFFFFF", tags: [] },
  { chain: "Degen", chainId: 666666666, type: "mainnet", icon: "degen.png", fee: 20, backgroundColor: "#A36EFE", color: "#FFFFFF", tags: [] },
  { chain: "Xai", chainId: 660279, type: "mainnet", icon: "xai.svg", fee: 1, backgroundColor: "#F30019", color: "#FFFFFF", tags: [] },
  { chain: "Kava", chainId: 2222, type: "mainnet", icon: "kava.svg", fee: 0.02, backgroundColor: "#FF443F", color: "#FFFFFF", tags: [] },
  { chain: "Aurora", chainId: 1313161554, type: "mainnet", icon: "aurora.svg", fee: 0.000025, backgroundColor: "#59A540", color: "#FFFFFF", tags: [] },
  { chain: "ZetaChain", chainId: 7000, type: "mainnet", icon: "zetachain.svg", fee: 0.5, backgroundColor: "#005741", color: "#FFFFFF", tags: [] },
  { chain: "Cronos", chainId: 25, type: "mainnet", icon: "cronos.png", fee: 1, backgroundColor: "#000000", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Botanix", chainId: 3637, type: "mainnet", icon: "botanix.png", fee: 0.000005, backgroundColor: "#FACD02", color: "#000000", tags: [] },
  { chain: "Katana", chainId: 747474, type: "mainnet", icon: "katana.svg", fee: 0.000005, backgroundColor: "#F4FF00", color: "#000000", tags: ["hot"] },
  { chain: "Plume", chainId: 98866, type: "mainnet", icon: "plume.jpg", fee: 0.03, backgroundColor: "#FF3C00", color: "#FFFFFF", tags: ["hot"] },
  { chain: "XDC", chainId: 50, type: "mainnet", icon: "xdc.jpg", fee: 0.03, backgroundColor: "#244C80", color: "#FFFFFF", tags: [] },
  { chain: "Mezo", chainId: 31612, type: "mainnet", icon: "mezo.jpg", fee: 0.03, backgroundColor: "#FF004C", color: "#FFFFFF", tags: [] },
  { chain: "Kaia", chainId: 8217, type: "mainnet", icon: "kaia.jpg", fee: 0.025, backgroundColor: "#BFF009", color: "#000000", tags: [] },
  { chain: "JuChain", chainId: 210000, type: "mainnet", icon: "juchain.jpg", fee: 0.01, backgroundColor: "#153BFE", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Mitosis", chainId: 124816, type: "mainnet", icon: "mitosis.jpg", fee: 0.2, backgroundColor: "#5E5DF7", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Sahara AI", chainId: 3132023, type: "mainnet", icon: "sahara.png", fee: 0.2, backgroundColor: "#F8FF98", color: "#000000", tags: [] },
  { chain: "Somnia", chainId: 5031, type: "mainnet", icon: "somnia.svg", fee: 0.05, backgroundColor: "#483BF6", color: "#FFFFFF", tags: [] },
  { chain: "Plasma", chainId: 9745, type: "mainnet", icon: "plasma.jpg", fee: 0.04, backgroundColor: "#162f29", color: "#FFFFFF", tags: [] },
  { chain: "Gate Layer", chainId: 10088, type: "mainnet", icon: "gatelayer.jpg", fee: 0.005, backgroundColor: "#000000", color: "#FFFFFF", tags: [] },
  { chain: "0G Mainnet", chainId: 16661, type: "mainnet", icon: "0g.png", fee: 0.025, backgroundColor: "#BA51FA", color: "#FFFFFF", tags: [] },
  { chain: "Zero Network", chainId: 543210, type: "mainnet", icon: "zeronetwork.jpg", fee: 0.000025, backgroundColor: "#000000", color: "#FFFFFF", tags: [] },
  { chain: "Humanity Protocol", chainId: 6985385, type: "mainnet", icon: "humanityprotocol.jpg", fee: 0.3, backgroundColor: "#BA5400", color: "#FFFFFF", tags: [] },
  { chain: "Zora", chainId: 7777777, type: "mainnet", icon: "zora.jpg", fee: 0.000025, backgroundColor: "#3566E6", color: "#FFFFFF", tags: [] },
];

const testnetOptions: DeployOption[] = [
  { chain: "Sepolia Testnet", chainId: 11155111, type: "testnet", icon: "sepolia.png", fee: 0.00005, backgroundColor: "#627EEA", color: "#FFFFFF", tags: [] },
  { chain: "Monad Testnet", chainId: 10143, type: "testnet", icon: "monad.png", fee: 0.01, backgroundColor: "#8070F2", color: "#FFFFFF", tags: [] },
  { chain: "Rise Testnet", chainId: 11155931, type: "testnet", icon: "rise.svg", fee: 0.0001, backgroundColor: "#7A67E5", color: "#FFFFFF", tags: [] },
  { chain: "Pharos Testnet", chainId: 688688, type: "testnet", icon: "pharos.png", fee: 0.005, backgroundColor: "#0007B8", color: "#FFFFFF", tags: [] },
  { chain: "Citrea Testnet", chainId: 5115, type: "testnet", icon: "citrea.png", fee: 0.000005, backgroundColor: "#E47530", color: "#FFFFFF", tags: [] },
  { chain: "Moca Testnet", chainId: 5151, type: "testnet", icon: "moca.png", fee: 0.00002, backgroundColor: "#C15F97", color: "#FFFFFF", tags: [] },
  { chain: "MegaETH Testnet", chainId: 6342, type: "testnet", icon: "megaeth.png", fee: 0.00001, backgroundColor: "#DFD9D9", color: "#000000", tags: [] },
  { chain: "XOS Testnet", chainId: 1267, type: "testnet", icon: "xos.png", fee: 0.00005, backgroundColor: "#000000", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Block Chain Testkek", chainId: 6231991, type: "testnet", icon: "blockchain.jpg", fee: 0.00002, backgroundColor: "#0000FF", color: "#FFFFFF", tags: [] },
  { chain: "Fluent Testnet", chainId: 20994, type: "testnet", icon: "fluent.jpg", fee: 0.000025, backgroundColor: "#000000", color: "#FFFFFF", tags: [] },
  { chain: "Giwa Testnet", chainId: 91342, type: "testnet", icon: "giwa.jpg", fee: 0.000015, backgroundColor: "#FFFFFF", color: "#000000", tags: [] },
  { chain: "Neura Testnet", chainId: 267, type: "testnet", icon: "neura.jpg", fee: 0.000004, backgroundColor: "#7FFF76", color: "#000000", tags: ["hot"] },
  { chain: "KiteAI Testnet", chainId: 2368, type: "testnet", icon: "kiteai.jpg", fee: 0.0001, backgroundColor: "#000000", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Kii Testnet", chainId: 1336, type: "testnet", icon: "kii.jpg", fee: 0.000025, backgroundColor: "#332976", color: "#FFFFFF", tags: [] },
  { chain: "Nitro Graph Testnet", chainId: 200024, type: "testnet", icon: "nitrograph.jpg", fee: 0.00005, backgroundColor: "#FC2E00", color: "#FFFFFF", tags: [] },
  { chain: "Base Sepolia Testnet", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0.00025, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["hot"] },
  { chain: "OP Sepolia Testnet", chainId: 11155420, type: "testnet", icon: "optimism.png", fee: 0.00025, backgroundColor: "#FF0420", color: "#FFFFFF", tags: [] },
  { chain: "Ink Sepolia Testnet", chainId: 763373, type: "testnet", icon: "ink.svg", fee: 0.00025, backgroundColor: "#9E7CEB", color: "#FFFFFF", tags: [] },
  { chain: "Unichain Sepolia Testnet", chainId: 1301, type: "testnet", icon: "unichain.png", fee: 0.00025, backgroundColor: "#F51BBD", color: "#FFFFFF", tags: [] },
  { chain: "Soneium Minato Testnet", chainId: 1946, type: "testnet", icon: "soneium.svg", fee: 0.00025, backgroundColor: "#6398C7", color: "#FFFFFF", tags: [] },
  { chain: "Lisk Sepolia Testnet", chainId: 4202, type: "testnet", icon: "lisk.svg", fee: 0.00025, backgroundColor: "#FFFFFF", color: "#000000", tags: [] },
  { chain: "Sova Sepolia Testnet", chainId: 120893, type: "testnet", icon: "sova.png", fee: 0.00025, backgroundColor: "#84F29C", color: "#000000", tags: [] },
  { chain: "Pharos Atlantic Testnet", chainId: 688689, type: "testnet", icon: "pharos.png", fee: 0.003, backgroundColor: "#0007B8", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Arc Testnet", chainId: 5042002, type: "testnet", icon: "arc.jpg", fee: 0.0005, backgroundColor: "#3D6A8D", color: "#FFFFFF", tags: ["hot"] },
  { chain: "IOPn Testnet", chainId: 984, type: "testnet", icon: "iopn.jpg", fee: 0.005, backgroundColor: "#000000", color: "#FFFFFF", tags: ["hot"] },
  { chain: "Stable Testnet", chainId: 2201, type: "testnet", icon: "stable.jpg", fee: 0.001, backgroundColor: "#053F30", color: "#FFFFFF", tags: ["new", "hot"] },
  { chain: "Rayls Testnet", chainId: 123123, type: "testnet", icon: "rayls.jpg", fee: 0.005, backgroundColor: "#EDFB51", color: "#000000", tags: ["new", "hot"] }
];

const baseLearnOptions: DeployOption[] = [
  { chain: "Basic Math", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.BASIC_MATH, args: [], description: "Perform safe addition and subtraction with overflow and underflow detection using unchecked arithmetic." },
  { chain: "Control Structures", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.CONTROL_STRUCTURES, args: [], description: "Practice if-else flows, assertions, and revert handling with structured control logic." },
  { chain: "Employee Storage", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.EMPLOYEE_STORAGE, args: [1000, "Pat", 50000, 112358132134], description: "Learn how to optimize storage and enforce limits through controlled updates and low-level inspection." },
  { chain: "Arrays Exercise", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.ARRAYS_EXERCISE, args: [], description: "Work with arrays, timestamps, and sender tracking while practicing loops and calldata." },
  { chain: "Favorite Records", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.FAVORITE_RECORDS, args: [approvedRecords], description: "Practice mappings, calldata, and user-specific storage in a music-themed exercise." },
  { chain: "Garage Manager", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.GARAGE_MANAGER, args: [], description: "Store, update, and reset your personal car collection using structs, mappings, and index-based validation." },
  { chain: "Inheritance Submission", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.INHERITANCE_SUBMISSION, args: [], description: "Model employee types and reporting structures using abstract contracts and inheritance. Involves deploying three distinct contracts." },
  { chain: "Imports Exercise", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.IMPORTS_EXERCISE, args: [], description: "Practice importing modules, working with structs, and applying library functions to calldata." },
  { chain: "Error Triage Exercise", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.ERROR_TRIAGE_EXERCISE, args: [], description: "Practice conditional arithmetic, array pop behavior, and modifier application using pure and stateful functions." },
  { chain: "Address Book Factory", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.ADDRESS_BOOK_FACTORY, args: [], description: "Create, retrieve, and delete contact records with owner-only access and indexed lookup." },
  { chain: "Unburnable Token", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.UNBURNABLE_TOKEN, args: [], description: "Manage token claiming and transfers with one-time access, balance tracking, and guarded logic." },
  { chain: "Weighted Voting", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.WEIGHTED_VOTING, args: ["Test Weighted", "TESTW"], description: "Implement token-weighted voting with quorum thresholds, custom errors, and per-issue tracking." },
  { chain: "Haiku NFT", chainId: 84532, type: "testnet", icon: "base.jpg", fee: 0, backgroundColor: "#0000FF", color: "#FFFFFF", tags: ["baseLearn"], deployType: DeployTypes.HAIKU_NFT, args: ["Test Haiku NFT", "HAIKU"], description: "Mint and manage unique three-line records as NFTs, enforcing line-level uniqueness and ownership." }
];

export const deployOptions: DeployOption[] = [...mainnetOptions, ...testnetOptions, ...baseLearnOptions];
